ctrl_interface=/var/run/wpa_supplicant
update_config=1
device_name=Linux
device_type=10-0050F204-5 #如果没有这个信息部分手机pin方式不能连接 不弹出pin输入窗口
# config_methods=virtual_display keypad #pin方式
config_methods=virtual_display keypad virtual_push_button #pbc方式 实测对使用指令连接的case这个config可以兼容pin和pbc 只对手机有影响
p2p_listen_reg_class=81
p2p_listen_channel=1
p2p_oper_reg_class=81
p2p_oper_channel=1
p2p_go_ht40=1
p2p_no_group_iface=1 #启用之后使用p2p_add_group不会创建新的网卡接口
p2p_go_intent=15